/* eslint-disable */
// Auto-generated stub for development build
// Real file is generated by `npx convex dev`

const activityFeed_ = { list: "activityFeed:list" as any, create: "activityFeed:create" as any };
const bookings_ = { list: "bookings:list" as any, getById: "bookings:getById" as any, create: "bookings:create" as any, update: "bookings:update" as any, cancel: "bookings:cancel" as any, getUpcoming: "bookings:getUpcoming" as any, getByTechnician: "bookings:getByTechnician" as any, updateTechNotes: "bookings:updateTechNotes" as any, updateStatus: "bookings:updateStatus" as any, getTodayCount: "bookings:getTodayCount" as any };
const calls_ = { list: "calls:list" as any, getById: "calls:getById" as any, getTodayStats: "calls:getTodayStats" as any };
const companies_ = { getBySlug: "companies:getBySlug" as any, getCompany: "companies:getCompany" as any, updateCompany: "companies:updateCompany" as any };
const companyFeatures_ = { listByCompany: "companyFeatures:listByCompany" as any, update: "companyFeatures:update" as any, create: "companyFeatures:create" as any };
const companyPlans_ = { getByCompany: "companyPlans:getByCompany" as any, create: "companyPlans:create" as any, update: "companyPlans:update" as any };
const dashboard_ = { getKPIs: "dashboard:getKPIs" as any, getRecentActivity: "dashboard:getRecentActivity" as any };
const intakeSessions_ = { list: "intakeSessions:list" as any, getById: "intakeSessions:getById" as any, create: "intakeSessions:create" as any, update: "intakeSessions:update" as any, createFromWeb: "intakeSessions:createFromWeb" as any, assignTech: "intakeSessions:assignTech" as any, markResolved: "intakeSessions:markResolved" as any, escalate: "intakeSessions:escalate" as any };
const memberships_ = { getByClerkUserId: "memberships:getByClerkUserId" as any, getMembers: "memberships:getMembers" as any, getCurrentUser: "memberships:getCurrentUser" as any, inviteMember: "memberships:inviteMember" as any, updateRole: "memberships:updateRole" as any, removeMember: "memberships:removeMember" as any };
const notifications_ = { list: "notifications:list" as any, markRead: "notifications:markRead" as any, markAllRead: "notifications:markAllRead" as any, getUnreadCount: "notifications:getUnreadCount" as any };
const onboarding_ = { createCompany: "onboarding:createCompany" as any, createOwnerMembership: "onboarding:createOwnerMembership" as any, initializeFeatures: "onboarding:initializeFeatures" as any, activateCompany: "onboarding:activateCompany" as any };
const seed_ = { seedDemoData: "seed:seedDemoData" as any };

export const api = {
  activityFeed: activityFeed_,
  bookings: bookings_,
  calls: calls_,
  companies: companies_,
  companyFeatures: companyFeatures_,
  companyPlans: companyPlans_,
  dashboard: dashboard_,
  intakeSessions: intakeSessions_,
  memberships: memberships_,
  notifications: notifications_,
  onboarding: onboarding_,
  seed: seed_,
};

export const internal = {} as any;
