/* eslint-disable */
// Auto-generated stub - real file generated by `npx convex dev`
export const query = (config: any) => config.handler;
export const mutation = (config: any) => config.handler;
export const internalQuery = (config: any) => config.handler;
export const internalMutation = (config: any) => config.handler;
export const action = (config: any) => config.handler;
export const httpAction = (config: any) => config.handler;
